---
version: '3.7'
services:
  # Service image
  app:
    image: pipefish:latest
    build: app
    environment:
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - CI
    env:
       TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH"
    volumes:
      - type: bind
        source: .
        target: /workspace
