---
version: '3.7'
services:
  # Service image
  app:
    image: pipefish:latest
    build: app
    environment:
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - CI
    volumes:
      - type: bind
        source: .
        target: /workspace
